### ISSUE TITLE
python3.7版本 alipy3.3.17版本出现签名失败问题

### ISSUE THREAD

**Issue by edisonmiao** [alipay/alipay-sdk-python-all#8]
我已经加了hash_method但是并没有什么用
 /Users/elaine/.virtualenvs/webdepenv/lib/python3.7/site-packages/alipay/aop/api/DefaultAlipayClient.py in __prepare_request_params sign = sign_with_rsa2(self.__config.app_private_key, sign_content, self.__config.charset)
/Users/elaine/.virtualenvs/webdepenv/lib/python3.7/site-packages/alipay/aop/api/util/SignatureUtils.py in sign_with_rsa2 signature = rsa.sign(sign_content, rsa.PrivateKey.load_pkcs1(private_key, format='PEM'), hash_method='SHA-256')
/Users/elaine/.virtualenvs/webdepenv/lib/python3.7/site-packages/rsa/key.py in load_pkcs1
 return method(keyfile)
/Users/elaine/.virtualenvs/webdepenv/lib/python3.7/site-packages/rsa/key.py in _load_pkcs1_pem return cls._load_pkcs1_der(der)
/Users/elaine/.virtualenvs/webdepenv/lib/python3.7/site-packages/rsa/key.py in _load_pkcs1_der key = cls(*as_ints)

**Comment by D4vid-Z** [comment]
@edisonmiao 同问题，请问目前有解决吗？如何解决呢？
```
Traceback (most recent call last):
  File "/Users/david/repos/platform/.env/lib/python3.6/site-packages/alipay/aop/api/DefaultAlipayClient.py", line 125, in __prepare_request_params
    sign = sign_with_rsa2(self.__config.app_private_key, sign_content, self.__config.charset)
  File "/Users/david/repos/platform/.env/lib/python3.6/site-packages/alipay/aop/api/util/SignatureUtils.py", line 50, in sign_with_rsa2
    signature = rsa.sign(sign_content, rsa.PrivateKey.load_pkcs1(private_key, format='PEM'), 'SHA-256')
  File "/Users/david/repos/platform/.env/lib/python3.6/site-packages/rsa/key.py", line 118, in load_pkcs1
    return method(keyfile)
  File "/Users/david/repos/platform/.env/lib/python3.6/site-packages/rsa/key.py", line 560, in _load_pkcs1_pem
    return cls._load_pkcs1_der(der)
  File "/Users/david/repos/platform/.env/lib/python3.6/site-packages/rsa/key.py", line 495, in _load_pkcs1_der
    key = cls(*as_ints)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Sequence'

```

**Comment by edisonmiao** [comment]
我已经解决了 原因是密钥问题。你要重新下载阿里的生成私钥和公钥的的软件 然后不要使用java适用那个 换一个就可以解决

**Comment by D4vid-Z** [comment]
> 我已经解决了 原因是密钥问题。你要重新下载阿里的生成私钥和公钥的的软件 然后不要使用java适用那个 换一个就可以解决

谢谢，那我去试试🙏
